ydlidar_x2_node:
  ros__parameters:
    port: /dev/ttyUSB1
    frame_id: laser_frame
    baudrate: 115200
    scan_frequency: 7.0
    angle_min: -180.0
    angle_max: 180.0
    range_min: 0.10
    range_max: 8.0
